# 池化层

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X,pool_size,mode='max'):
    '''
    :param X:输入
    :param pool_size:(1,1)池化窗口的高和宽
    :param mode:最大池化、平均池化...
    :return:
    '''
    p_h,p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

In [2]:
X = torch.tensor([[0.0,1,2],[3,4,5],[6,7,8]])
pool2d(X,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [3]:
pool2d(X,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

In [12]:
# 批量大小是1，通道是1
X = torch.arange(16,dtype=torch.float32).reshape(1,1,4,4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [7]:
# 用3x3的窗口，深度学习框架中步幅和池化窗口的大小相同
pool2d = nn.MaxPool2d(2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [8]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [9]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [13]:
print(f'拼接前：{X.shape}')
X = torch.cat((X,X+1),1)
print(f'拼接后：{X.shape}')

拼接前：torch.Size([1, 1, 4, 4])
拼接后：torch.Size([1, 2, 4, 4])


In [15]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
print(f'池化后：{pool2d(X).shape}')


池化后：torch.Size([1, 2, 2, 2])
