In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,X):
        return X-X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

Y = net(torch.rand(4,8))
Y.mean()

torch.Size([4, 128])

In [6]:
class MyLinear(nn.Module):
    def __init__(self,in_uints,uints):
        '''
        初始化
        :param in_uints: 输入维度
        :param uints: 输出维度
        '''
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_uints,uints))
        self.bias = nn.Parameter(torch.randn(uints,))

    def forward(self,X):
        linear = torch.matmul(X,self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[-0.2133, -0.4351,  1.7793],
        [ 1.0718,  0.0592,  2.0451],
        [-0.7455,  0.8554, -0.7589],
        [-1.3653,  0.5469, -1.5268],
        [-0.3870,  0.4922, -0.7323]], requires_grad=True)

In [7]:
dense(torch.rand(2,5))

tensor([[0.0000, 2.0327, 2.2516],
        [0.0000, 2.2982, 1.6498]])

In [12]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.0000],
        [1.4079]])