# 读写文件

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
# 把tensor x存储子在当前文件夹下的x-file里
torch.save(x,'x-file')

x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [2]:
# 存储list
y = torch.zeros(4)
# 会覆盖原本内容
torch.save([x,y],'x-file')
x2,y2 = torch.load('x-file')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [3]:
# 构造字典
mydict = {'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [5]:
# 加载和保存模型参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)

    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net =MLP()
X = torch.randn(size = (2,20))
Y = net(X)

tensor([[ 0.2381, -0.3050,  0.0362,  0.1353, -0.0230,  0.0271, -0.0344,  0.0843,
          0.1215, -0.2997],
        [ 0.2706, -0.3343,  0.0945,  0.0573,  0.1239, -0.0210,  0.0857,  0.1263,
          0.1916, -0.2120]], grad_fn=<AddmmBackward0>)

In [6]:
# net.state_dict()取出所有参数的名字字符串到他参数的映射
torch.save(net.state_dict(),'mlp.params')

In [13]:
# 先生成一个MLP实例
clone = MLP()
# 将存储的参数读取出来到MLP中
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])